### ISSUE TITLE
Create a new file in the arrays folder and inside write the code for the program, Move all the negative elements to one side of the array 

### ISSUE THREAD

**Issue by shuchitpant** [shuchitpant/Learning_dsnalgo#20]
## Move all the negative elements to one side of the   array
it is important to include the file in the ARRAY folder

**Comment by swati-gwc** [comment]
Please assign me this issue, I would like to contribute to this.

**Comment by sbindal057** [comment]
please assign me this issue.

**Comment by shuchitpant** [comment]
just make a pull request and I'll merge it
