### ISSUE TITLE
Create a new file and write the code for the program:: Find the Union and Intersection of the two sorted arrays.-- INSIDE the ARRAY folder only.

### ISSUE THREAD

**Issue by shuchitpant** [shuchitpant/Learning_dsnalgo#21]
## Find the Union and Intersection of the two sorted   arrays.
--------------------------------------------------------------------

you can find the code on GfG if you want, but try solving on your own.

**Comment by palakdavda22** [comment]
I want to work on this, can you assign me this?

**Comment by shuchitpant** [comment]
yeah
you can too!
just make a pull request
